# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mmar < Formula
  desc "mmar is a zero-dependancy, self-hostable, cross-platform HTTP tunnel that exposes your localhost to the world on a public URL."
  homepage "https://mmar.dev"
  version "0.2.0"
  license "AGPLv3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yusuf-musleh/mmar/releases/download/v0.2.0/mmar_Darwin_x86_64.tar.gz"
      sha256 "76ecf0888893ed8dac0175f308691c93f33940fc3dacfd79dc65ee8a58e17cde"

      def install
        bin.install "mmar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yusuf-musleh/mmar/releases/download/v0.2.0/mmar_Darwin_arm64.tar.gz"
      sha256 "d0c2cc5e4da3a01f23ff040613a3e90405003f4fd178b2e0e2294cb0a49e24d9"

      def install
        bin.install "mmar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yusuf-musleh/mmar/releases/download/v0.2.0/mmar_Linux_x86_64.tar.gz"
        sha256 "f22eaf9bdf3531a0900191469a4931cfd5fe2a888e9bb99b84b950b1e08cd1a8"

        def install
          bin.install "mmar"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yusuf-musleh/mmar/releases/download/v0.2.0/mmar_Linux_arm64.tar.gz"
        sha256 "6b5523814de1a98dd776cc5f76a9fa61a1495cd174b367164e6d469088b42049"

        def install
          bin.install "mmar"
        end
      end
    end
  end

  test do
    system "#{bin}/mmar version"
  end
end
