# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mmar < Formula
  desc "mmar is a zero-dependancy, self-hostable, cross-platform HTTP tunnel that exposes your localhost to the world on a public URL."
  homepage "https://mmar.dev"
  version "0.2.3"
  license "AGPLv3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yusuf-musleh/mmar/releases/download/v0.2.3/mmar_Darwin_x86_64.tar.gz"
      sha256 "d9db1df0e923103be0180ff1df2c4abf987e5e8ff3fef97559c23d4ab8c58af4"

      def install
        bin.install "mmar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yusuf-musleh/mmar/releases/download/v0.2.3/mmar_Darwin_arm64.tar.gz"
      sha256 "8167acece77cafda6832904b58a8bfeb079682218707087d4cbb7c37c71cd985"

      def install
        bin.install "mmar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yusuf-musleh/mmar/releases/download/v0.2.3/mmar_Linux_x86_64.tar.gz"
        sha256 "7996d580212571b60aaf86859c86a3729eb97d1929fef2f15d14c1dc008cbf95"

        def install
          bin.install "mmar"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yusuf-musleh/mmar/releases/download/v0.2.3/mmar_Linux_arm64.tar.gz"
        sha256 "bd7c509f950ed6c72a13b3c11acbae2d478663248cebb333165519490b908534"

        def install
          bin.install "mmar"
        end
      end
    end
  end

  test do
    system "#{bin}/mmar version"
  end
end
